/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/common/Alert/Alert.vue')['default']
    Button: typeof import('./components/common/buttons/Button/Button.vue')['default']
    ButtonBack: typeof import('./components/common/buttons/ButtonBack.vue')['default']
    Checkbox: typeof import('./components/common/inputs/CheckboxField/Checkbox.vue')['default']
    CheckboxField: typeof import('./components/common/inputs/CheckboxField/CheckboxField.vue')['default']
    ExampleMultiForm: typeof import('./components/examples/multiForm/ExampleMultiForm.vue')['default']
    ExampleSingleForm: typeof import('./components/examples/singleForm/ExampleSingleForm.vue')['default']
    FieldWrapper: typeof import('./components/common/inputs/FieldWrapper/FieldWrapper.vue')['default']
    FileInput: typeof import('./components/common/inputs/FileInputField/FileInput.vue')['default']
    FormActionPanel: typeof import('./components/common/panels/FormActionPanel/FormActionPanel.vue')['default']
    FormActions: typeof import('./components/examples/shared/FormActions.vue')['default']
    FormControl: typeof import('./components/common/forms/FormControl.vue')['default']
    FormPanel: typeof import('./components/common/panels/FormPanel/FormPanel.vue')['default']
    FormWrapper: typeof import('./components/common/forms/FormWrapper/FormWrapper.vue')['default']
    HeaderPanel: typeof import('./components/common/panels/HeaderPanel/HeaderPanel.vue')['default']
    IsdavimasForm: typeof import('./components/examples/multiForm/IsdavimasForm.vue')['default']
    ModalInfo: typeof import('./components/modals/ModalInfo.vue')['default']
    NumberStepper: typeof import('./components/common/inputs/NumberStepperField/NumberStepper.vue')['default']
    NumberStepperField: typeof import('./components/common/inputs/NumberStepperField/NumberStepperField.vue')['default']
    OrderFormActions: typeof import('./components/examples/shared/OrderFormActions.vue')['default']
    PapildomosPaslaugosForm: typeof import('./components/examples/multiForm/PapildomosPaslaugosForm.vue')['default']
    PaslaugosUzsakymasForm: typeof import('./components/examples/multiForm/PaslaugosUzsakymasForm.vue')['default']
    Radio: typeof import('./components/common/inputs/RadioFields/Radio.vue')['default']
    RadioButtonsField: typeof import('./components/common/inputs/RadioFields/RadioButtonsField.vue')['default']
    RadioField: typeof import('./components/common/inputs/RadioFields/RadioField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableArea: typeof import('./components/common/inputs/shared/SearchableArea/SearchableArea.vue')['default']
    SearchField: typeof import('./components/common/inputs/SearchField.vue')['default']
    SelectField: typeof import('./components/common/inputs/SelectField/SelectField.vue')['default']
    ServiceForm: typeof import('./components/examples/singleForm/ServiceForm.vue')['default']
    StepFormLayout: typeof import('./components/layouts/StepFormLayout.vue')['default']
    Tab: typeof import('./components/common/tabs/Tab.vue')['default']
    TerminaiForm: typeof import('./components/examples/multiForm/TerminaiForm.vue')['default']
    Test: typeof import('./components/common/Test.vue')['default']
    TextField: typeof import('./components/common/inputs/TextField/TextField.vue')['default']
    Tooltip: typeof import('./components/common/tooltip/Tooltip.vue')['default']
    VerticalStepper: typeof import('./components/common/steppers/VerticalStepper/VerticalStepper.vue')['default']
    VueDatepicker: typeof import('./components/common/inputs/DatePickerField/VueDatepicker.vue')['default']
  }
}
